language: csharp
solution: JValueMasker.sln
install:
  - nuget restore JValueMasker.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release JValueMasker.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./JValueMaskerTests/bin/Release/JValueMaskerTests.dll
