language: csharp
mono: 5.18.0
dotnet: 2.1.502

install:
  - dotnet restore ./src/JValueMasker.sln

script:
  - dotnet build ./src/JValueMasker.sln
  - dotnet test ./src/JValueMaskerTests/JValueMaskerTests.csproj
