language: csharp
mono: 5.18.0
dotnet: 2.1.502

install:
  - nuget restore ./src/JValueMasker.sln

script:
  - dotnet test ./src/JValueMaskerTests/JValueMaskerTests.csproj
  - msbuild /p:Configuation=Release ./src/JValueMasker.sln
