image: Visual Studio 2017

before_build:
  - nuget restore ./src
  - choco install opencover.portable
  - choco install codecov

build:
  project: ./src/JValueMasker.sln
  verbosity: minimal

test_script:
  - OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console" -targetargs:".\src\JValueMaskerTests\bin\Debug\netcoreapp2.1\JValueMaskerTests.dll -noshadow" -filter:"+[JValueMaskter]* -[*Tests]*"  -output:".\JValueMaskerTests_coverage.xml"
  - codecov -f "JValueMaskerTests_coverage.xml
