version: 0.1.6.{build}

branches:
  only:
    - master

image: Visual Studio 2017

before_build:
  - dotnet tool install -g coveralls.net --version 1.0.0
  - nuget restore ./src

nuget:
  account_feed: true
  project_feed: true

# build:
#   project: ./src/JValueMasker.sln
#   verbosity: minimal

build:
  publish_nuget: true
  verbosity: minimal

test_script:
  - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[xunit*]*" ./src/JValueMaskerTests/JValueMaskerTests.csproj
  - csmacnz.coveralls --opencover --useRelativePaths -i C:\projects\jvaluemasker\src\JValueMaskerTests\coverage.opencover.xml

artifacts:
  - path: '**\*.nupkg'

deploy:
  provider: NuGet
  server:
  api_key:
    secure: hp46mSR3sfuUE4ICs+zWj3NHqXU840yF6tlT+iyezgj7jSUxwhIYh1XHdhCN1rhP
  skip_symbols: true
  artifact: /.*\.nupkg/
