image: Visual Studio 2017

before_build:
  - nuget restore ./src
  - choco install opencover.portable
  - choco install codecov

build:
  project: ./src/JValueMasker.sln
  verbosity: minimal

test_script:
  # - OpenCover.Console.exe -register:user -target:"C:\Program Files\dotnet\dotnet.exe" -targetargs:".\src\JValueMaskerTests\bin\Debug\netcoreapp2.1\JValueMaskerTests.dll" -filter:"+[*]* -[*Tests]*" -output:".\JValueMaskerTests_coverage.xml"
  - dotnet test /p:CollectCoverage=true /p:Exclude="[xunit*]*" ./src/JValueMaskerTests/JValueMaskerTests.csproj
  - cat ./src/JValueMaskerTests/coverage.json
  - codecov -f ./src/JValueMaskerTests/coverage.json
